/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.AjouterAchatForm;

public class AjouterAchatAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AjouterAchatForm ajouterAchatForm = (AjouterAchatForm) form;// TODO Auto-generated method stub
		
		// Obtenir les données a partir du formulaire 
		int codeArt = Integer.parseInt(ajouterAchatForm.getNom());
		int qteAchete = Integer.parseInt(ajouterAchatForm.getQuantite());
		String dateReception = ajouterAchatForm.getDate();
		
		// Insérer les nouveaux données dans la base de données 
		int isAdded = CDB.Acess_donner.mise_ajour("INSERT INTO `achats`(`codeArt`, `qteAchete`, `dateReception`) VALUES ('"+codeArt+"','"+qteAchete+"','"+dateReception+"')","g_stock");
		
		//Obtention d'une session 
		HttpSession Session = request.getSession();
		
		//  Si "added" retourne "success" , afficher "alert"
		if(isAdded != 0){
			Session.setAttribute("alert", "Ajouter");
		} else {
			Session.setAttribute("alert", "AjouterF");
		}
	return mapping.findForward("success");
	}
}