/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.ModifierAchatForm;


public class ModifierAchatAction extends Action {

	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifierAchatForm modifierAchatForm = (ModifierAchatForm) form;// TODO Auto-generated method stub
		
		// Obtenir les données a partir du formulaire
		int codeAchat = Integer.parseInt(modifierAchatForm.getCodeAchat());
		int codeArt = Integer.parseInt(modifierAchatForm.getNom());
		int qteAchete = Integer.parseInt(modifierAchatForm.getQuantite());
		String dateReception = modifierAchatForm.getDate();
		
		// Insérer les nouveaux données dans la base de données 
		int isModified = CDB.Acess_donner.mise_ajour("UPDATE `achats` SET `codeArt`='"+codeArt+"', `qteAchete`='"+qteAchete+"',`dateReception`='"+dateReception+"' WHERE `codeAchat` = '"+codeAchat+"'", "g_stock");
		
		// Obtention d'une session
		HttpSession Session = request.getSession();
		
		// Si "modified" retourne "success" , afficher "alert"
		if(isModified != 0){
			Session.setAttribute("alert", "Modifier");
		} else {
			Session.setAttribute("alert", "ModifierF");
		}
		
		return mapping.findForward("success");
	}
}