/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.ModifierInvForm;


public class ModifierInvAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ModifierInvForm modifierInvForm = (ModifierInvForm) form;// TODO Auto-generated method stub
		
		// Obtenir les données a partir du formulaire 
		int codeInv = Integer.parseInt(modifierInvForm.getCodeInv());
		int codeArt = Integer.parseInt(modifierInvForm.getNom());
		int qteArt = Integer.parseInt(modifierInvForm.getQuantite());
		String descInv = modifierInvForm.getDescription();
		String dateInv = modifierInvForm.getDate();
		
		// Insérer les nouveaux données dans la base de données
		int isModified = CDB.Acess_donner.mise_ajour("UPDATE `inventaire` SET `codeArt`='"+codeArt+"', `qteArt`='"+qteArt+"',`descInv`='"+descInv+"',`dateInv`='"+dateInv+"' WHERE `codeInv` = '"+codeInv+"'", "g_stock");
		
		// Obtention d'une session 
		HttpSession Session = request.getSession();
		
		// Si "modified" retourne "success" , afficher "alert"
		if(isModified != 0){
			Session.setAttribute("alert", "Modifier");
		} else {
			Session.setAttribute("alert", "ModifierF");
		}
		
		return mapping.findForward("success");
	}
}