/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.SupprimerAchatForm;

public class SupprimerAchatAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SupprimerAchatForm supprimerAchatForm = (SupprimerAchatForm) form;// TODO Auto-generated method stub
		
		// Deleting from database
		int isDeleted = CDB.Acess_donner.mise_ajour("DELETE FROM `achats` WHERE `codeAchat`= '"+supprimerAchatForm.getCodeAchat()+"'","g_stock");
		
		// Getting session
		HttpSession Session = request.getSession();
		
		// if deleted returns success else return fail
		if(isDeleted != 0){
			Session.setAttribute("alert", "Supprimer");
		} else {
			Session.setAttribute("alert", "SupprimerF");
		}
		
	return mapping.findForward("success");
	}
}